import { rasterStage } from "./raster-stage.ts";
import { type Editor, layerName } from "@diagra/core";

export const RASTER_SCALES = [0.5, 0.75, 1, 1.5, 2, 3, 4] as const;

/** Read only the root viewport of an SVG produced by our deterministic serializer.
 * This is not an external SVG parser or sanitizer. */
export function svgRasterDimensions(svg: string) {
  const viewport = /^<svg\s[^>]*\bviewBox="([^"]+)"/.exec(svg)?.[1];
  const values = viewport?.trim().split(/\s+/).map(Number) ?? [];
  const width = values[2];
  const height = values[3];
  if (
    values.length !== 4 ||
    !values.every(Number.isFinite) ||
    !width ||
    !height ||
    width <= 0 ||
    height <= 0
  )
    throw new Error("The generated SVG has no valid export viewport.");
  return { width, height };
}

/** Capture a consistent immutable export without changing document or selection. */
export function rasterExportSnapshot(
  editor: Editor,
  options: {
    readonly artboardId?: string;
    readonly wholePage?: boolean;
    readonly padding?: number;
    readonly background?: string | null;
  } = {},
) {
  const {
    artboardId,
    wholePage = false,
    padding = 0,
    background = null,
  } = options;
  if (!Number.isFinite(padding) || padding < 0 || padding > 256)
    throw new Error("PNG padding must be between 0 and 256 canvas units.");
  if (background !== null && !/^#[0-9a-f]{6}$/i.test(background))
    throw new Error(
      "PNG background must be a six-digit hex color or transparent.",
    );
  const svg = wholePage
    ? editor.exportPageSvg({ padding, background })
    : artboardId
      ? editor.exportArtboardSvg(artboardId, { background })
      : editor.exportSelectionSvg({ padding, background });
  if (!svg) throw new Error("Choose visible artwork to export.");
  const ids = [...editor.selection.ids()];
  const element = editor.store.get(
    artboardId ?? (ids.length === 1 ? (ids[0] ?? "") : ""),
  );
  return {
    svg,
    ...svgRasterDimensions(svg),
    name: wholePage
      ? (editor.store.getPage(editor.currentPageId)?.name ?? "page")
      : element
        ? layerName(element)
        : "selection",
  };
}

/** Bound allocations before creating browser image/canvas resources. */
export function rasterDimensions(width: number, height: number, scale: number) {
  if (
    ![width, height, scale].every(Number.isFinite) ||
    width <= 0 ||
    height <= 0 ||
    !RASTER_SCALES.some((value) => value === scale)
  )
    throw new Error(
      "PNG export requires positive dimensions and a supported density scale.",
    );
  const pixels = {
    width: Math.ceil(width * scale),
    height: Math.ceil(height * scale),
  };
  if (
    pixels.width > 8192 ||
    pixels.height > 8192 ||
    pixels.width * pixels.height > 32_000_000
  )
    throw new Error(
      "PNG export is limited to 8192 pixels per side and 32 megapixels. Choose a smaller scale or use SVG.",
    );
  return pixels;
}

/** Only call with SVG generated by the editor, never arbitrary external SVG. */
export async function rasterizeSvg(
  svg: string,
  scale: number,
  signal?: AbortSignal,
): Promise<Blob> {
  const viewport = svgRasterDimensions(svg);
  const size = rasterDimensions(viewport.width, viewport.height, scale);
  if (signal?.aborted) throw new Error("PNG export cancelled.");
  const image = new Image();
  const canvas = document.createElement("canvas");
  let url: string | undefined;
  try {
    url = URL.createObjectURL(new Blob([svg], { type: "image/svg+xml" }));
    image.src = url;
    await rasterStage(() => image.decode(), signal);
    if (signal?.aborted) throw new Error("PNG export cancelled.");
    canvas.width = size.width;
    canvas.height = size.height;
    const context = canvas.getContext("2d");
    if (!context)
      throw new Error("This browser cannot create a PNG drawing surface.");
    context.drawImage(image, 0, 0, size.width, size.height);
    const blob = await rasterStage(
      () =>
        new Promise<Blob>((resolve, reject) =>
          canvas.toBlob(
            (blob) =>
              blob
                ? resolve(blob)
                : reject(new Error("This browser could not encode the PNG.")),
            "image/png",
          ),
        ),
      signal,
    );
    if (signal?.aborted) throw new Error("PNG export cancelled.");
    return blob;
  } finally {
    canvas.width = 0;
    canvas.height = 0;
    if (url) URL.revokeObjectURL(url);
    image.src = "";
  }
}

export function assetFileName(name: string, scale: number): string {
  const base = Array.from(name, (char) =>
    char.charCodeAt(0) < 32 || char.charCodeAt(0) === 127 ? "-" : char,
  )
    .join("")
    .replace(/[<>:"/\\|?*]/g, "-")
    .replace(/^\.+|[. ]+$/g, "")
    .trim()
    .slice(0, 100);
  return `${base || "artboard"}@${scale}x.png`;
}
